<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dnh</string>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>Danmakufu</string>
	<key>firstLineMatch</key>
	<string>^\s*(#TouhouDanmakufu|script_|//dnh_include).*</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.danmakufu</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.danmakufu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\.?\d*\b</string>
			<key>name</key>
			<string>constant.numeric.danmakufu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|pi)\b</string>
			<key>name</key>
			<string>constant.language.danmakufu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(EV)_[\w_]*\b</string>
			<key>name</key>
			<string>variable.parameter.event.danmakufu</string>
			<key>comment</key>
			<string>Only variable.parameter for the color choice</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(alternative|ascent|break|case|descent|else|if|in|local|loop|return|others|times|while|yield)\b</string>
			<key>name</key>
			<string>keyword.control.flow.danmakufu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*#(TouhouDanmakufu|ScriptVersion|ID|Title|Text|Image|System|Background|BGM|Player|ReplayName)\b</string>
			<key>name</key>
			<string>keyword.control.header.danmakufu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*#include\b</string>
			<key>name</key>
			<string>keyword.control.include.danmakufu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(add|append|concatenate|divide|erase|index|length|multiply|not|negative|power|predecessor|remainder|result|slice|successor|subtract)\b</string>
			<key>name</key>
			<string>keyword.operator.textual.danmakufu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>==|!=|&lt;=|&rt;=|&lt;|&rt;|\|\||&amp;&amp;|~</string>
			<key>name</key>
			<string>keyword.operator.logical.danmakufu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+=|\+|-=|-|\*=|\*|/=|/|%|\^|\(\||\|\)</string>
			<key>name</key>
			<string>keyword.operator.symbol.danmakufu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(let|real|char|boolean)\b</string>
			<key>name</key>
			<string>storage.type.variable.danmakufu</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.danmakufu</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)"</string>
			<key>end</key>
			<string>(?&lt;!\\)"</string>
			<key>name</key>
			<string>string.quoted.double.danmakufu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^@(Initialize|Loading|Event|MainLoop|Finalize)\b</string>
			<key>name</key>
			<string>entity.name.function.predefined.danmakufu</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(min|max|log|log10|cos|sin|tan|acos|asin|atan|atan2|rand|round|truncate|ceil|floor|absolute|modc|InstallFont|ToString|IntToString|itoa|rtoa|rtos|vtos|atoi|ator|TrimString|SplitString)\(</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.library.danmakufu</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(function|sub|task)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.danmakufu</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\{</string>
			<key>name</key>
			<string>meta.function.danmakufu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([A-Za-z_]\w*)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.danmakufu</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.function.identifier.danmakufu</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b[A-Za-z_]\w*\b</string>
							<key>name</key>
							<string>variable.parameter.danmakufu</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Za-z_]\w*\s*</string>
					<key>name</key>
					<string>entity.name.function.danmakufu</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.danmakufu</string>
	<key>uuid</key>
	<string>062ce88a-0eba-444e-b6bb-250c9d7f94ce</string>
</dict>
</plist>
